import type { Metadata } from "next";
import { RecoilRoot } from "recoil";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SessionProvider } from "next-auth/react";
import SessionWrapper from "@/lib/sessionProvider";
import { Toaster } from "@/components/ui/toaster";
import { RecoilRootProvider } from "@/components/recoil-root/recoil-root";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${inter.className} p-0 sm:p-10`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SessionWrapper>
            <RecoilRootProvider>{children}</RecoilRootProvider>
          </SessionWrapper>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
